version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
      - run: npm run stylelint
      - run: npm run test:jsdom -- --coverage
      - run: npm run test:server -- --coverage
      - run: npx codecov
      - run:
          name: serve
          command: node server
          background: true
      - run: sleep 3
      - run: npm run monitors
  publish-storybook:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx storybook-to-ghpages
workflows:
  version: 2
  commit: # this workflow runs on every commit
    jobs:
      - test
      - publish-storybook:
          requires:
            - test
          filters:
            branches:
              only:
                - master